pull_request_rules:
  - name: Dependabot automatic merges
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Linting Checks
      - check-success=Validate PR title
      - "check-success=Test (Node: 14.x)"
      - "check-success=Test (Node: 16.x)"
      - "check-success=Test (Node: 18.x)"
      - "#check-failure=0"
    actions:
      merge:
        method: squash
